// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://addfjstppedbotannczp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkZGZqc3RwcGVkYm90YW5uY3pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2MTAxNzEsImV4cCI6MjA4OTE4NjE3MX0.TCmyudRmKLnNZ2KoWlmTMY4W14Lf2AyToN_W6-1E7CA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});